### ISSUE TITLE
complied failed on centos7,  the gcc version is 12.1.0.

### ISSUE THREAD

**Issue by Nic-bit** [gottingen/turbo#54]
![截屏2024-01-09 18 32 09](https://github.com/gottingen/turbo/assets/71635218/66923a46-e7ef-4bc4-ba2d-d980618c931c)

**Comment by Nic-bit** [comment]
export PATH=/opt/compiler/gcc-12/bin:$PATH  before  "carbin install",  include<string> in file hash_engine.cc.

**Comment by lilothar** [comment]
on gcc 12, implicit include <string> failed ,add #include <string> to hash_engine.h will be ok

**Comment by lilothar** [comment]
fix it
