### ISSUE TITLE
object_pool and resource_pool call the clear_resources don't destory  object

### ISSUE THREAD

**Issue by Nic-bit** [gottingen/turbo#57]
turbo::ResourceId<Nic> id;
    Nic *p = turbo::get_resource(&id, 1, 2);
    if(0 == turbo::return_resource(id)) {
        turbo::println("return resource");
    } 
    turbo::clear_resources<Nic>();
    return 0;

**Comment by lilothar** [comment]
call turbo::get_resource just as new a object, delete object should call return_resource to return the resource to pool

**Comment by lilothar** [comment]
further more that the memory pool may move to an other repo focus on memory, this repo focus on high performance containers
